; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -O3 -march=amdgcn -mcpu=gfx942  -mtriple amdgcn-amd-hmcsa -global-isel < %s | FileCheck %s

; function attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare <1 x float> @llvm.maxnum.v1f32(<1 x float>, <1 x float>) #0

; function attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare float @llvm.maxnum.f32(float, float) #0

define void @foo.bb374(<1 x float> %i466, ptr %out) {
; CHECK-LABEL: foo.bb374:
; CHECK:       ; %bb.0: ; %newfuncroot
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_max_f32_e32 v0, v0, v0
; CHECK-NEXT:    v_mov_b32_e32 v4, v1
; CHECK-NEXT:    v_mov_b32_e32 v5, v2
; CHECK-NEXT:    v_max_f32_e32 v0, 0, v0
; CHECK-NEXT:    flat_store_dword v[4:5], v0
; CHECK-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; CHECK-NEXT:    s_setpc_b64 s[30:31]
newfuncroot:
  %i497 = tail call <1 x float> @llvm.maxnum.v1f32(<1 x float> %i466, <1 x float> zeroinitializer)
  %i503 = extractelement <1 x float> %i497, i64 0
  %i507 = tail call float @llvm.maxnum.f32(float %i503, float 0.000000e+00)
  store float %i507, ptr %out
  ret void
}

attributes #0 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
